In [152]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [153]:
df=pd.read_csv("bengaluru_house_prices.csv")
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00


In [154]:
df.groupby('area_type')['area_type'].count()


area_type
Built-up  Area          2418
Carpet  Area              87
Plot  Area              2025
Super built-up  Area    8790
Name: area_type, dtype: int64

In [155]:
df2=df.drop([ 'society', 'balcony', 'availability','area_type'], axis='columns')
df2

,location,size,total_sqft,bath,price
0,Electronic City Phase II,2 BHK,1056,2.0,39.07
1,Chikka Tirupathi,4 Bedroom,2600,5.0,120.00
2,Uttarahalli,3 BHK,1440,2.0,62.00
3,Lingadheeranahalli,3 BHK,1521,3.0,95.00
4,Kothanur,2 BHK,1200,2.0,51.00
...,...,...,...,...,...
13315,Whitefield,5 Bedroom,3453,4.0,231.00
13316,Richards Town,4 BHK,3600,5.0,400.00
13317,Raja Rajeshwari Nagar,2 BHK,1141,2.0,60.00
13318,Padmanabhanagar,4 BHK,4689,4.0,488.00


In [156]:
df2.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [157]:
df2.dropna(inplace=True)
final=df2


In [158]:
final=df2

In [159]:
l=[]
for i in final['size']:
    l.append(int(i[0]))



In [160]:
for i in l:
    if isinstance(i , str):
        print(i)

In [161]:
final['size']=l

In [162]:
final

,location,size,total_sqft,bath,price
0,Electronic City Phase II,2,1056,2.0,39.07
1,Chikka Tirupathi,4,2600,5.0,120.00
2,Uttarahalli,3,1440,2.0,62.00
3,Lingadheeranahalli,3,1521,3.0,95.00
4,Kothanur,2,1200,2.0,51.00
...,...,...,...,...,...
13315,Whitefield,5,3453,4.0,231.00
13316,Richards Town,4,3600,5.0,400.00
13317,Raja Rajeshwari Nagar,2,1141,2.0,60.00
13318,Padmanabhanagar,4,4689,4.0,488.00


In [163]:
final['bath'].unique()

array([ 2.,  5.,  3.,  4.,  6.,  1.,  9.,  8.,  7., 11., 10., 14., 27.,
       12., 16., 40., 15., 13., 18.])

In [164]:
final[final['bath']>10]

,location,size,total_sqft,bath,price
938,5th Phase JP Nagar,9,1260,11.0,290.0
1078,BTM 1st Stage,9,3300,14.0,500.0
1718,2Electronic City Phase II,2,8000,27.0,230.0
1768,1 Ramamurthy Nagar,1,1200,11.0,170.0
1953,KR Puram,8,1200,12.0,110.0
1979,Hongasandra,8,990,12.0,120.0
3096,Jp nagar 8th Phase .,1,12000,12.0,525.0
3379,1Hanuman Nagar,1,2000,16.0,490.0
3609,Koramangala Industrial Layout,1,10000,16.0,550.0
4684,Munnekollal,4,2400,40.0,660.0


In [165]:
x=final[final.bath>15]
x

,location,size,total_sqft,bath,price
1718,2Electronic City Phase II,2,8000,27.0,230.0
3379,1Hanuman Nagar,1,2000,16.0,490.0
3609,Koramangala Industrial Layout,1,10000,16.0,550.0
4684,Munnekollal,4,2400,40.0,660.0
11559,1Kasavanhalli,1,1200,18.0,200.0


In [166]:
def is_float(x):
   try:
         float(x)
   except:
        return False
   return True
   


In [167]:
final[final['total_sqft'].apply(is_float)==False]

,location,size,total_sqft,bath,price
30,Yelahanka,4,2100 - 2850,4.0,186.000
122,Hebbal,4,3067 - 8156,4.0,477.000
137,8th Phase JP Nagar,2,1042 - 1105,2.0,54.005
165,Sarjapur,2,1145 - 1340,2.0,43.490
188,KR Puram,2,1015 - 1540,2.0,56.800
...,...,...,...,...,...
12975,Whitefield,2,850 - 1060,2.0,38.190
12990,Talaghattapura,3,1804 - 2273,3.0,122.000
13059,Harlur,2,1200 - 1470,2.0,72.760
13265,Hoodi,2,1133 - 1384,2.0,59.135


In [168]:
def convert(x):
    t=x.split('-')
    if len(t)==2:
        return (float(t[0])+float(t[1]))/2
    try:
        return float(x)
    except:
        return None

In [169]:
a=final.copy()

In [170]:
a['total_sqft']=a['total_sqft'].apply(convert)

In [171]:
a[a['total_sqft'].apply(is_float)==False]

,location,size,total_sqft,bath,price


In [172]:
a

,location,size,total_sqft,bath,price
0,Electronic City Phase II,2,1056.0,2.0,39.07
1,Chikka Tirupathi,4,2600.0,5.0,120.00
2,Uttarahalli,3,1440.0,2.0,62.00
3,Lingadheeranahalli,3,1521.0,3.0,95.00
4,Kothanur,2,1200.0,2.0,51.00
...,...,...,...,...,...
13315,Whitefield,5,3453.0,4.0,231.00
13316,Richards Town,4,3600.0,5.0,400.00
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,60.00
13318,Padmanabhanagar,4,4689.0,4.0,488.00


In [173]:
final=a
final

,location,size,total_sqft,bath,price
0,Electronic City Phase II,2,1056.0,2.0,39.07
1,Chikka Tirupathi,4,2600.0,5.0,120.00
2,Uttarahalli,3,1440.0,2.0,62.00
3,Lingadheeranahalli,3,1521.0,3.0,95.00
4,Kothanur,2,1200.0,2.0,51.00
...,...,...,...,...,...
13315,Whitefield,5,3453.0,4.0,231.00
13316,Richards Town,4,3600.0,5.0,400.00
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,60.00
13318,Padmanabhanagar,4,4689.0,4.0,488.00


In [174]:
final['pps']=final['price']*100000/final['total_sqft']

In [175]:
final['location']=df.location

In [176]:
final

,location,size,total_sqft,bath,price,pps
0,Electronic City Phase II,2,1056.0,2.0,39.07,3699.810606
1,Chikka Tirupathi,4,2600.0,5.0,120.00,4615.384615
2,Uttarahalli,3,1440.0,2.0,62.00,4305.555556
3,Lingadheeranahalli,3,1521.0,3.0,95.00,6245.890861
4,Kothanur,2,1200.0,2.0,51.00,4250.000000
...,...,...,...,...,...,...
13315,Whitefield,5,3453.0,4.0,231.00,6689.834926
13316,Richards Town,4,3600.0,5.0,400.00,11111.111111
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,60.00,5258.545136
13318,Padmanabhanagar,4,4689.0,4.0,488.00,10407.336319


In [177]:
final.location = final.location.apply(lambda x: x.strip())

In [178]:
final.location.unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], shape=(1293,), dtype=object)

In [179]:
ls=final.groupby('location')['location'].count().sort_values(ascending=True)

In [180]:
ls.head(20)

location
AECS LAYOUT A-BLOCK Singasandra    1
AGB Layout                         1
Aavalahalli                        1
Abshot Layout                      1
Achins Road                        1
Adarsh Nagar                       1
6th Block Jayanagar                1
6th Block Rajaji Nagar             1
asha township, off hennur road     1
banashankari stage iii sa          1
basaveshwarnagar                   1
beml layout, basaveshwara nagar    1
2nd phase jp nagar, jp nagar       1
3rd Block HBR Layout               1
3rd Phase Iti Layout               1
3rd Stage Raja Rajeshwari Nagar    1
Indiranagar HAL 2nd Stage          1
elachenahalli                      1
ittamadu                           1
kadubisnahalli                     1
Name: location, dtype: int64

In [181]:
len(ls[ls<=10])

1052

In [182]:
ls10=ls[ls<=10]
ls10

location
AECS LAYOUT A-BLOCK Singasandra     1
AGB Layout                          1
Aavalahalli                         1
Abshot Layout                       1
Achins Road                         1
                                   ..
Dodsworth Layout                   10
Ganga Nagar                        10
Naganathapura                      10
Sadashiva Nagar                    10
Nagadevanahalli                    10
Name: location, Length: 1052, dtype: int64

In [183]:
final.location = final.location.apply( lambda x: "other" if x in ls10 else x)

In [184]:
len(final.location.unique())

242

In [185]:
final['pps'].quantile(0.999)

np.float64(50959.580419581405)

In [186]:
final.describe()

,size,total_sqft,bath,price,pps
count,13246.000000,13200.000000,13246.000000,13246.000000,1.320000e+04
mean,2.778046,1555.302783,2.692586,112.389392,7.920759e+03
std,1.170077,1237.323445,1.341506,149.076587,1.067272e+05
min,1.000000,1.000000,1.000000,8.000000,2.678298e+02
25%,2.000000,1100.000000,2.000000,50.000000,4.267701e+03
50%,3.000000,1275.000000,2.000000,72.000000,5.438331e+03
75%,3.000000,1672.000000,3.000000,120.000000,7.317073e+03
max,9.000000,52272.000000,40.000000,3600.000000,1.200000e+07


In [187]:
final2=final[final.total_sqft/final['size']>=300]

In [188]:
final2

,location,size,total_sqft,bath,price,pps
0,Electronic City Phase II,2,1056.0,2.0,39.07,3699.810606
1,Chikka Tirupathi,4,2600.0,5.0,120.00,4615.384615
2,Uttarahalli,3,1440.0,2.0,62.00,4305.555556
3,Lingadheeranahalli,3,1521.0,3.0,95.00,6245.890861
4,Kothanur,2,1200.0,2.0,51.00,4250.000000
...,...,...,...,...,...,...
13315,Whitefield,5,3453.0,4.0,231.00,6689.834926
13316,other,4,3600.0,5.0,400.00,11111.111111
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,60.00,5258.545136
13318,Padmanabhanagar,4,4689.0,4.0,488.00,10407.336319


In [189]:
final2.describe()

,size,total_sqft,bath,price,pps
count,12472.000000,12472.000000,12472.000000,12472.000000,12472.000000
mean,2.639112,1590.579998,2.576732,111.394903,6321.224286
std,0.946938,1261.028999,1.187855,152.346877,4188.395933
min,1.000000,300.000000,1.000000,9.000000,267.829813
25%,2.000000,1116.000000,2.000000,49.000000,4210.526316
50%,3.000000,1300.000000,2.000000,70.000000,5295.544522
75%,3.000000,1700.000000,3.000000,115.000000,6929.522602
max,9.000000,52272.000000,40.000000,3600.000000,176470.588235


In [190]:
final3=final2[final2['bath']<14]

In [191]:
min=final3.pps.quantile(0.003)
min

np.float64(2086.3030303030305)

In [192]:
max=final3.pps.quantile(0.93)
max

np.float64(11714.99510230736)

In [193]:
final4=final3[(final3.pps>min) & (final3.pps<max)]

In [194]:
final4

,location,size,total_sqft,bath,price,pps
0,Electronic City Phase II,2,1056.0,2.0,39.07,3699.810606
1,Chikka Tirupathi,4,2600.0,5.0,120.00,4615.384615
2,Uttarahalli,3,1440.0,2.0,62.00,4305.555556
3,Lingadheeranahalli,3,1521.0,3.0,95.00,6245.890861
4,Kothanur,2,1200.0,2.0,51.00,4250.000000
...,...,...,...,...,...,...
13315,Whitefield,5,3453.0,4.0,231.00,6689.834926
13316,other,4,3600.0,5.0,400.00,11111.111111
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,60.00,5258.545136
13318,Padmanabhanagar,4,4689.0,4.0,488.00,10407.336319


In [195]:
x = pd.get_dummies(final4['location'], drop_first=True,dtype='int')

In [196]:
x

,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,7th Phase JP Nagar,8th Phase JP Nagar,9th Phase JP Nagar,AECS Layout,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
13316,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13317,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13318,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [197]:
final5=pd.concat([final4,x],axis='columns')

In [198]:
final5

,location,size,total_sqft,bath,price,pps,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
0,Electronic City Phase II,2,1056.0,2.0,39.07,3699.810606,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Chikka Tirupathi,4,2600.0,5.0,120.00,4615.384615,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Uttarahalli,3,1440.0,2.0,62.00,4305.555556,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Lingadheeranahalli,3,1521.0,3.0,95.00,6245.890861,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Kothanur,2,1200.0,2.0,51.00,4250.000000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Whitefield,5,3453.0,4.0,231.00,6689.834926,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
13316,other,4,3600.0,5.0,400.00,11111.111111,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,60.00,5258.545136,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13318,Padmanabhanagar,4,4689.0,4.0,488.00,10407.336319,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [199]:
from sklearn.linear_model import LinearRegression as lr
model=lr()

In [200]:
input=final5.drop(['price','pps','location'],axis='columns')
target=final5['price']

In [201]:
from sklearn.model_selection import train_test_split as tts

In [202]:
x1,x2,y1,y2=tts(input,target,test_size=0.2)

In [203]:
model.fit(x1,y1)

LinearRegression()

In [204]:
model.score(x2,y2)

0.8024801542223485

In [205]:
model.score(x1,y1)

0.8214690695520322

In [206]:
model.score(input,target)

0.8182832015393109

In [207]:
from sklearn.model_selection import ShuffleSplit as ss
from sklearn.model_selection import cross_val_score as cvs

In [208]:
cv=ss(n_splits=5, test_size=0.2, random_state=0)

score=cvs(lr(), input, target, cv=cv)

In [209]:
score.mean()

np.float64(0.8260695560396693)

In [210]:
from sklearn.model_selection import GridSearchCV as gscv 
from sklearn.linear_model import Lasso 
from sklearn.tree import DecisionTreeRegressor as dtr

In [211]:
def bestmodel(input,target):
    algos={
        'lr':{
            'model':lr(),
            'parmas':{
                'fit_intercept':[True,False],
            }
        },
        'lasso':{
            'model': Lasso(),
            'parmas':{
                'alpha':[1,2,3,4,5],
                'selection':['cyclic','random']
            }
        },
        'dtr':{
            'model':dtr(),
            'parmas':{
                'splitter':['best','random'],
                'max_depth':[2,3,4,5,6,7,8,9,10],
            }   
        }  
        }
    scores=[]
    for a,c in algos.items():
        gs=gscv(c['model'],c['parmas'],cv=cv)
        gs.fit(input,target)
        scores.append({
            'model':a,
            'best_score':gs.best_score_,
            'best_params':gs.best_params_
            })
    return pd.DataFrame(scores,columns=['model','best_score','best_params'])


In [212]:
bestmodel(input,target)

,model,best_score,best_params
0,lr,0.826229,{'fit_intercept': False}
1,lasso,0.799971,"{'alpha': 1, 'selection': 'random'}"
2,dtr,0.801375,"{'max_depth': 6, 'splitter': 'best'}"


In [213]:
model.score(x2,y2)

0.8024801542223485

In [214]:
import pickle

with open('model.pickle','wb') as f:
    pickle.dump(model,f)

In [215]:
with open('model.pickle','rb') as f:
    model= pickle.load(f)

model

LinearRegression()

In [216]:
model.score(input,target)

0.8182832015393109

In [217]:
np.where(input)

(array([    0,     0,     0, ..., 11553, 11553, 11553], shape=(46213,)),
 array([ 0,  1,  2, ...,  1,  2, 75], shape=(46213,)))

In [218]:
y_predicted=model.predict(input)

In [219]:
pd.DataFrame( y_predicted, target )

,0
price,
39.07,33.853599
120.00,110.896103
62.00,63.534937
95.00,97.877910
51.00,55.719162
...,...
231.00,230.606080
400.00,246.241866
60.00,44.222862


In [220]:
input.columns

Index(['size', 'total_sqft', 'bath', '1st Phase JP Nagar',
       '2nd Phase Judicial Layout', '2nd Stage Nagarbhavi',
       '5th Block Hbr Layout', '5th Phase JP Nagar', '6th Phase JP Nagar',
       '7th Phase JP Nagar',
       ...
       'Vishveshwarya Layout', 'Vishwapriya Layout', 'Vittasandra',
       'Whitefield', 'Yelachenahalli', 'Yelahanka', 'Yelahanka New Town',
       'Yelenahalli', 'Yeshwanthpur', 'other'],
      dtype='object', length=243)

In [221]:
np.where(input.columns=='2nd Stage Nagarbhavi')[0][0]

np.int64(5)

In [222]:
a=input.head(1)

In [223]:
a.shape

(1, 243)

In [224]:
model.predict(a)

array([33.85359922])

In [225]:
target

0         39.07
1        120.00
2         62.00
3         95.00
4         51.00
          ...  
13315    231.00
13316    400.00
13317     60.00
13318    488.00
13319     17.00
Name: price, Length: 11554, dtype: float64

In [250]:
def predictp(location,s, total_sqft, bath):
    lx=np.where(input.columns==location)[0][0]
    x=np.zeros(len(input.columns))
    x[0]=s
    x[1]=total_sqft
    x[2]=bath
    if lx>=0:
        x[lx]=1
    b = pd.DataFrame(np.array([x]))
    result = model.predict(b)

    return result[0]

predictp("1st Phase JP Nagar", 2 , 1200, 2)

TypeError: object of type 'NoneType' has no len()

In [248]:
pd.DataFrame(b)

,0,1,2,3,4,5,6,7,8,9,...,233,234,235,236,237,238,239,240,241,242
0,2.0,1056.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [249]:
a

,size,total_sqft,bath,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,7th Phase JP Nagar,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
0,2,1056.0,2.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
